glacier-modding/RPKG-Tool

.gitignore
rpkg-cli/rpkg-cli.vcxproj
rpkg-cli/rpkg-cli.vcxproj.filters

Prerequisite to building on Linux.

[Build] Don't include removed header files

---

rpkg-gui/HashCalculator.xaml
rpkg-gui/HashCalculator.xaml.cs
rpkg_src/rpkg_dll.cpp
rpkg_src/rpkg_dll.h

Rewrote the Hash Calculator utility in the GUI a bit
- It is now quicker.
- It now displays '(calculating...)' while it is calculating.

Speed up the GUI hash calculator

---

rpkg_src/extract_locr_to_json_from.cpp
rpkg_src/rebuild_locr_from_json_from.cpp

See title. Let it build first.

[RPKG] Fix extracting/rebuilding for 10 lang. H3 LOCR files

---

rpkg_src/extract_locr_to_json_from.cpp

See title, accidentally removed it before.

[RPKG] Re-add extracting of 9 lang. H3 LOCR

---

rpkg_src/rpkg_dll.cpp
rpkg_src/rpkg_dll.h

Fixes my hash calculation stuff that only worked in debug configuration.
C++ bools don't do well with C# pinvoke as it turns out.

[RPKG] Fix new hashcalc giving bogus results

---

rpkg_src/temp.cpp
rpkg_src/thirdparty/zhmtools/ResourceGenerator.h
rpkg_src/thirdparty/zhmtools/ResourceLib_HM2016.h

Updates ResourceLib to support the latest version and uses the [compatibility generator](https://github.com/OrfeasZ/ZHMTools/releases/tag/v2.0.0).

[RPKG] Update ResourceLib

---

rpkg-gui/MainWindow.xaml.cs

Stops crashing when you click on a TEXT file from a game that isn't Hitman 3.

[GUI] Make the Image Viewer load on click

---

rpkg-gui/MainWindow.xaml.cs

The hash list update message is redundant.
There is a pull request to update it.
Would you like to merge it now and update the message to make it less redundant?
Click Merge pull request to have it merged automatically.
The software will automatically build when done.

[GUI] Less redundant hash list update message

---

rpkg-gui/EntityBrickEditor.xaml.cs

[GUI] Fix underscores in sub-entity name

---

rpkg-gui/EntityBrickEditor.xaml.cs

[GUI] aaaaaaaaaaaaaa

---

rpkg-gui/MainWindow.xaml.cs
rpkg_src/console.cpp
rpkg_src/extract_all_hash_depends_from.cpp
rpkg_src/rpkg_function.h
rpkg_src/task.cpp

Added a button to extract non-base hash depends (those not in chunk0/chunk1).

[GUI] Non-base chunk recursive extraction of hash depends

---

rpkg-cli/rpkg-cli.vcxproj
rpkg-cli/rpkg-cli.vcxproj.filters
rpkg/rpkg.vcxproj
rpkg/rpkg.vcxproj.filters
rpkg_src/console.cpp
rpkg_src/extract_from_rpkgs.cpp
rpkg_src/rpkg_function.h
rpkg_src/task.cpp

[RPKG/CLI] Add -extract_from_rpkgs command

---

rpkg_src/compute_ioi_hash.cpp
rpkg_src/compute_ioi_hash_from_file.cpp
rpkg_src/compute_ioi_hash_string.cpp

Some based changes that will have substantial effect

.push_back() has inconsistent complexity in strings so replaced it

---

rpkg_src/extract_gfxf_from.cpp
rpkg_src/extract_locr_to_json_from.cpp
rpkg_src/extract_ores_from.cpp
rpkg_src/extract_prel_from.cpp
rpkg_src/extract_wwem_to_ogg_from.cpp
rpkg_src/file.h
rpkg_src/gpudevice.cpp
rpkg_src/search_hash_data.cpp
rpkg_src/texd.cpp
rpkg_src/text.cpp

This looks like a big PR, but really isn't.
The goal is to reduce nesting where possible by changing code from this format:
```cpp
void hello()
{
if (file_exists) {
// all the logic
} else { LOG_AND_EXIT("uh oh"); }
}
```
To this format:
```cpp
void hello()
{
ASSERT_EXISTS()
// all the logic
}
```
- It's shorter
- Less nesting = better readability

[RPKG] Reduce nesting in functions (first pass)

---

rpkg_src/extract_gfxf_from.cpp
rpkg_src/extract_locr_to_json_from.cpp
rpkg_src/extract_ores_from.cpp
rpkg_src/extract_prel_from.cpp
rpkg_src/extract_wwem_to_ogg_from.cpp
rpkg_src/file.h
rpkg_src/gpudevice.cpp
rpkg_src/search_hash_data.cpp
rpkg_src/texd.cpp
rpkg_src/text.cpp

Reverts glacier-modding/RPKG-Tool#50

Revert "[RPKG] Reduce nesting in functions (first pass)"

---

rpkg_src/console.cpp
rpkg_src/extract_all_hash_depends_from.cpp
rpkg_src/rpkg_function.h
rpkg_src/task.cpp

Oh, what am I saying? Of course you don't.

[RPKG] Add extract_non_chunk0_hash_depends_from command

---

src/extract_all_hash_depends_from.cpp

[RPKG] Critical hotfix for SMF

---

src/generate_hash_meta_json.cpp
src/hash_meta_to_json.cpp
src/json_to_hash_meta.cpp

As title:
Before:
```json
{
"hash_value": "000804A6A00A1A45",
"hash_offset": 200086824,
"hash_size": 2147484153,
"hash_resource_type": "ATMD",
"hash_reference_table_size": 31,
"hash_reference_table_dummy": 0,
"hash_size_final": 973,
"hash_size_in_memory": 4294967295,
"hash_size_in_video_memory": 4294967295,
"hash_reference_data": [
{
"hash": "[assembly:/sound/wwise/exportedwwisedata/events/animation/foley/environment_interactions/newspaper/play_fol_newspaper_open_hero.wwiseevent].pc_wwisebank",
"flag": "5F"
},
{
"hash": "[assembly:/sound/wwise/exportedwwisedata/events/animation/foley/environment_interactions/newspaper/play_fol_newspaper_pickup_hero.wwiseevent].pc_wwisebank",
"flag": "5F"
},
{
"hash": "[assembly:/sound/wwise/exportedwwisedata/events/animation/foley/genericfoley/anim_genfole …
```

[RPKG] Change hash_value in meta JSON to an IOI path

---

rpkg-gui/MainWindow.xaml.cs

Add disclaimer to QN JSON extract option

---

CMakeLists.txt

As title. Also "fixes" #94. Not exactly a bug, just a surprising use case.

[RPKG] Bump TonyTools Version
